name = "line-up"
version = "0.1.0"
defaultTargets = ["LineUpTest"]
testDriver = "LineUpTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "LineUp"

[[lean_exe]]
name = "LineUpTest"
root = "LineUpTest"
