name = "rational-numbers"
version = "0.1.0"
defaultTargets = ["RationalNumbersTest"]
testDriver = "RationalNumbersTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "RationalNumbers"

[[lean_exe]]
name = "RationalNumbersTest"
root = "RationalNumbersTest"
