name = "largest-series-product"
version = "0.1.0"
defaultTargets = ["LargestSeriesProductTest"]
testDriver = "LargestSeriesProductTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "LargestSeriesProduct"

[[lean_exe]]
name = "LargestSeriesProductTest"
root = "LargestSeriesProductTest"
