name = "raindrops"
version = "0.1.0"
defaultTargets = ["RaindropsTest"]
testDriver = "RaindropsTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Raindrops"

[[lean_exe]]
name = "RaindropsTest"
root = "RaindropsTest"
