name = "relative-distance"
version = "0.1.0"
defaultTargets = ["RelativeDistanceTest"]
testDriver = "RelativeDistanceTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "RelativeDistance"

[[lean_exe]]
name = "RelativeDistanceTest"
root = "RelativeDistanceTest"
