name = "bob"
version = "0.1.0"
defaultTargets = ["BobTest"]
testDriver = "BobTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Bob"

[[lean_exe]]
name = "BobTest"
root = "BobTest"
