name = "matrix"
version = "0.1.0"
defaultTargets = ["MatrixTest"]
testDriver = "MatrixTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Matrix"

[[lean_exe]]
name = "MatrixTest"
root = "MatrixTest"
