name = "leap"
version = "0.1.0"
defaultTargets = ["LeapTest"]
testDriver = "LeapTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Leap"

[[lean_exe]]
name = "LeapTest"
root = "LeapTest"
