name = "transpose"
version = "0.1.0"
defaultTargets = ["TransposeTest"]
testDriver = "TransposeTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Transpose"

[[lean_exe]]
name = "TransposeTest"
root = "TransposeTest"
