name = "grep"
version = "0.1.0"
defaultTargets = ["GrepTest"]
testDriver = "GrepTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Grep"

[[lean_exe]]
name = "GrepTest"
root = "GrepTest"
