name = "two-bucket"
version = "0.1.0"
defaultTargets = ["TwoBucketTest"]
testDriver = "TwoBucketTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "TwoBucket"

[[lean_exe]]
name = "TwoBucketTest"
root = "TwoBucketTest"
