name = "armstrong-numbers"
version = "0.1.0"
defaultTargets = ["ArmstrongNumbersTest"]
testDriver = "ArmstrongNumbersTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "ArmstrongNumbers"

[[lean_exe]]
name = "ArmstrongNumbersTest"
root = "ArmstrongNumbersTest"
