name = "clock"
version = "0.1.0"
defaultTargets = ["ClockTest"]
testDriver = "ClockTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Clock"

[[lean_exe]]
name = "ClockTest"
root = "ClockTest"
