name = "acronym"
version = "0.1.0"
defaultTargets = ["AcronymTest"]
testDriver = "AcronymTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Acronym"

[[lean_exe]]
name = "AcronymTest"
root = "AcronymTest"
