name = "allergies"
version = "0.1.0"
defaultTargets = ["AllergiesTest"]
testDriver = "AllergiesTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Allergies"

[[lean_exe]]
name = "AllergiesTest"
root = "AllergiesTest"
