name = "roman-numerals"
version = "0.1.0"
defaultTargets = ["RomanNumeralsTest"]
testDriver = "RomanNumeralsTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "RomanNumerals"

[[lean_exe]]
name = "RomanNumeralsTest"
root = "RomanNumeralsTest"
