name = "hello-world"
version = "0.1.0"
defaultTargets = ["HelloWorldTest"]
testDriver = "HelloWorldTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "HelloWorld"

[[lean_exe]]
name = "HelloWorldTest"
root = "HelloWorldTest"
