name = "secret-handshake"
version = "0.1.0"
defaultTargets = ["SecretHandshakeTest"]
testDriver = "SecretHandshakeTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "SecretHandshake"

[[lean_exe]]
name = "SecretHandshakeTest"
root = "SecretHandshakeTest"
