name = "sum-of-multiples"
version = "0.1.0"
defaultTargets = ["SumOfMultiplesTest"]
testDriver = "SumOfMultiplesTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "SumOfMultiples"

[[lean_exe]]
name = "SumOfMultiplesTest"
root = "SumOfMultiplesTest"
