name = "game-of-life"
version = "0.1.0"
defaultTargets = ["GameOfLifeTest"]
testDriver = "GameOfLifeTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "GameOfLife"

[[lean_exe]]
name = "GameOfLifeTest"
root = "GameOfLifeTest"
