name = "dnd-character"
version = "0.1.0"
defaultTargets = ["DndCharacterTest"]
testDriver = "DndCharacterTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "DndCharacter"

[[lean_exe]]
name = "DndCharacterTest"
root = "DndCharacterTest"
