name = "gigasecond"
version = "0.1.0"
defaultTargets = ["GigasecondTest"]
testDriver = "GigasecondTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Gigasecond"

[[lean_exe]]
name = "GigasecondTest"
root = "GigasecondTest"
