name = "flatten-array"
version = "0.1.0"
defaultTargets = ["FlattenArrayTest"]
testDriver = "FlattenArrayTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "FlattenArray"

[[lean_exe]]
name = "FlattenArrayTest"
root = "FlattenArrayTest"
