name = "word-count"
version = "0.1.0"
defaultTargets = ["WordCountTest"]
testDriver = "WordCountTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "WordCount"

[[lean_exe]]
name = "WordCountTest"
root = "WordCountTest"
