name = "reverse-string"
version = "0.1.0"
defaultTargets = ["ReverseStringTest"]
testDriver = "ReverseStringTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "ReverseString"

[[lean_exe]]
name = "ReverseStringTest"
root = "ReverseStringTest"
